/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DelenRouteImport } from './routes/delen'
import { Route as ReeksRouteImport } from './routes/reeks'
import { Route as ZoekenRouteImport } from './routes/zoeken'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DelenRoute = DelenRouteImport.update({
  id: '/delen',
  path: '/delen',
  getParentRoute: () => rootRouteImport,
} as any)
const ReeksRoute = ReeksRouteImport.update({
  id: '/reeks',
  path: '/reeks',
  getParentRoute: () => rootRouteImport,
} as any)
const ZoekenRoute = ZoekenRouteImport.update({
  id: '/zoeken',
  path: '/zoeken',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/delen': typeof DelenRoute
  '/reeks': typeof ReeksRoute
  '/zoeken': typeof ZoekenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/delen': typeof DelenRoute
  '/reeks': typeof ReeksRoute
  '/zoeken': typeof ZoekenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/delen': typeof DelenRoute
  '/reeks': typeof ReeksRoute
  '/zoeken': typeof ZoekenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/delen' | '/reeks' | '/zoeken'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/delen' | '/reeks' | '/zoeken'
  id: '__root__' | '/' | '/delen' | '/reeks' | '/zoeken'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DelenRoute: typeof DelenRoute
  ReeksRoute: typeof ReeksRoute
  ZoekenRoute: typeof ZoekenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delen': {
      id: '/delen'
      path: '/delen'
      fullPath: '/delen'
      preLoaderRoute: typeof DelenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reeks': {
      id: '/reeks'
      path: '/reeks'
      fullPath: '/reeks'
      preLoaderRoute: typeof ReeksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zoeken': {
      id: '/zoeken'
      path: '/zoeken'
      fullPath: '/zoeken'
      preLoaderRoute: typeof ZoekenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DelenRoute: DelenRoute,
  ReeksRoute: ReeksRoute,
  ZoekenRoute: ZoekenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
